### ISSUE TITLE
'+' sign in date input is removed from compValue

### ISSUE THREAD

**Issue by RoyLeibo** [thomaspoignant/scim2-parse-filter#153]
For input:
email eq "2016-07-23T18:17:38.372+00:00"
The output ignore the '+' sign in the date in the "compValue" attribute, so it ends up:

```
{
  "op": "eq",
  "attrPath": "email",
  "compValue": "2016-07-23T18:17:38.372 00:00"
}
```

Why is that?
If I understand the purpose of the lib correctly, it just a parse, shouldn't affect the values at all.

Thanks!

**Comment by thomaspoignant** [comment]
It maybe because of the regex parsing.
I will try to have a look at it _(but I have limited time recently)_, if you want feel free to open a PR for this.

**Comment by RoyLeibo** [comment]
@thomaspoignant 
After cloning the repo and try to reproduce it unsuccessfully, I saw the Nest is getting rid of it, not your lib :) 
Thank anyway!

**Comment by thomaspoignant** [comment]
@RoyLeibo good to hear that 👍
