### ISSUE TITLE
Feature Request: Stringify (reverse transform of parse)

### ISSUE THREAD

**Issue by patrickmcdougle-okta** [thomaspoignant/scim2-parse-filter#45]
Would you be interested in adding the reverse transform of parse? Such that given a scim AST as returned by parse() it would return the string that would generate it?

The use case I have is that I want to make a scim filter wizard that makes it easier for a non-technical person to write a scim filter string using dropdowns and text fields. This library works great for transforming the string representation into the AST, but not the reverse which I need.

Not necessarily asking the maintainers to do the work, just asking if a feature like this would be acceptable / mergeable into this library.

**Comment by thomaspoignant** [comment]
Hello Patrick,
Definitely it can be a great addition to the lib.

**Comment by thomaspoignant** [comment]
@patrickmcdougle-okta the v0.2.0 is released and available in npm.
